### ISSUE TITLE
Feed URL's are not showing content of sub category.

### ISSUE THREAD

**Issue by sajandara** [ahmedkaludi/gn-publisher#34]
Feed URLs are not showing the content of the sub-category if the permalink is customized and the parameter "category" is removed from the permalink.

Ref ticket: https://magazine3.in/conversation/66797?folder_id=27

**Comment by elifvish** [comment]
Parent category `name` is being fetched instead of `slug` [here](https://github.com/ahmedkaludi/gn-publisher/blob/main/class-gnpub-compat.php#L124).
Adding `true` parameter for `nicename`  fixes the issue.

Changing this -
`$parents = get_category_parents( $category->parent, false, '/' );`

to this -

`$parents = get_category_parents( $category->parent, false, '/', true );`


Fixes the issue.

**Comment by akshaywali** [comment]
Issue fixed in version 1.5.6 https://github.com/ahmedkaludi/gn-publisher/commit/82c3746a012eeb293427c41c008f421007ecfbf8

Thanks @elifvish for your fix

**Comment by akshaywali** [comment]
pushed in update 1.5.6
